import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Ensure the correct font weight and styles are used.
const poppins = Poppins({ subsets: ['latin'], weight: ['100','200','300', '400', '500', '600'] });

export const metadata: Metadata = {
  title: "VibeChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
